### ISSUE TITLE
유전 알고리즘 구현

### ISSUE THREAD

**Issue by minjune8506** [minjune8506/GeneticAvoidance#7]
- 유전 알고리즘 클래스로 구현
- 게임에 적용
- 신경망의 w 값들을 유전적으로 찾는다.
- 세대별 유전자 수는?

**Comment by SOLokill** [comment]
>유전자형 결정 
>초기 모집단 결정 
>개체 적합도 계산
>선택 수행(Selection)
>교차 처리(Crossover)
>변이 수행(Mutation)
